version: '2'

services:
  #
  # MySQL
  # #############################################
  mysql:
    image: mysql:5.6.35
    hostname: mysql
    stdin_open: true
    # tty: true
    ports:
      - "3306:3306"
    environment:
      TZ: "America/Sao_Paulo"
      #MYSQL_USER: user
      #MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_CLIENT: '%.%.%.%'
    volumes:
      - "./conf/mysql:/etc/mysql/conf.d"
      - "./data/mysql:/var/lib/mysql"

  #
  # CONTACTS API
  # #############################################
  contacts-api:
    image: tmm-node
    hostname: contacts-api
    ports:
      - 3000:3000
    environment:
      NODE_ENV: 'development'
      TZ: "America/Sao_Paulo"
    volumes:
      - "../:/var/www/html"
    command: >
       sh -c "ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime &&
       echo America/Sao_Paulo > /etc/timezone &&
       cd /var/www/html/contacts-api && npm start"
    depends_on:
      - mysql
    links:
      - mysql

  #
  # NGINX (External web border 80 and 443 ports)
  # #############################################
  nginx:
    image: contacts-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - "../:/var/www/html"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/nginx.d:/etc/nginx/conf.d"
      - "./conf/nginx/ssl-params.conf:/etc/nginx/ssl-params.conf"
      - "./conf/nginx/ssl:/etc/ssl"
    depends_on:
      - contacts-api
    links:
      - contacts-api