// contact
export const REQUEST_CONTACT_GROUPS = 'REQUEST_CONTACT_GROUPS'
export const RECEIVE_CONTACT_GROUPS = 'RECEIVE_CONTACT_GROUPS'
export const REQUEST_CONTACTS = 'REQUEST_CONTACTS'
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS'
export const REQUEST_CONTACT = 'REQUEST_CONTACT'
export const RECEIVE_CONTACT = 'RECEIVE_CONTACT'
export const RESET_CONTACT = 'RESET_CONTACT'
export const REQUEST_SAVE_CONTACT = 'REQUEST_SAVE_EXAME'
export const RECEIVE_SAVE_CONTACT = 'RECEIVE_SAVE_EXAME'

// phone
export const REQUEST_TYPES = 'REQUEST_TYPES'
export const RECEIVE_TYPES = 'RECEIVE_TYPES'
export const REQUEST_SAVE_PHONE = 'REQUEST_SAVE_PHONE'
export const RECEIVE_SAVE_PHONE = 'RECEIVE_SAVE_PHONE'

// toast
export const CHANGE_TOAST = 'CHANGE_TOAST'
